### PR TITLE
support loading checkpoint from GCS

### PR DESCRIPTION
**Pull request by tommadams**
This isn't read to push: the first model trained from the checkpoint performs badly in eval, which indicates that training isn't being resumed correctly.

Since the checkpoint files are large, we're going to store them on GCS instead of github. I've added a `ml_perf/get_data.py` script that grabs the checkpoint & training target from GCS and freezes the model protos.

### CODE REVIEW

**Comment by christ1ne** [comment]
Does this PR require python2? I used python3 and got the following error message. This is on GCP.


-------------:~/minigo$     BOARD_SIZE=9 python ml_perf/get_data.py
Making dir ml_perf/checkpoint
I0329 22:25:29.311440 139682405238528 utils.py:54] Running: gsutil  -m  cp  -r  gs://minigo-pub/ml_perf/checkpoint/
9  ml_perf/checkpoint
I0329 22:25:35.458297 139682405238528 utils.py:86] gsutil finished: 6.146 seconds
Making dir ml_perf/target
I0329 22:25:35.459384 139682405238528 utils.py:54] Running: gsutil  -m  cp  -r  gs://minigo-pub/ml_perf/target/9  m
l_perf/target
I0329 22:25:36.840321 139682405238528 utils.py:86] gsutil finished: 1.381 seconds
I0329 22:25:36.840956 139682405238528 utils.py:54] Running: python  freeze_graph.py  --model_path=ml_perf/target/9/
target  --use_tpu=False
Traceback (most recent call last):
  File "ml_perf/get_data.py", line 63, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "ml_perf/get_data.py", line 56, in main
    freeze_graph('ml_perf/target/{}/target'.format(N))
  File "ml_perf/get_data.py", line 42, in freeze_graph
    '--model_path={}'.format(path), '--use_tpu={}'.format(FLAGS.use_tpu)))
  File "./ml_perf/utils.py", line 102, in wait
    raise result
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./ml_perf/utils.py", line 72, in checked_run
    p.returncode, expand_cmd_str(cmd), stdout))
RuntimeError: Return code 1 from process: python  freeze_graph.py  --model_path=ml_perf/target/9/target  --use_tpu=
False
Traceback (most recent call last):
  File "freeze_graph.py", line 18, in <module>
    import dual_net
  File "/home/christine_cheng/minigo/dual_net.py", line 35, in <module>
    import features as features_lib
  File "/home/christine_cheng/minigo/features.py", line 29, in <module>
    import utils
  File "/home/christine_cheng/minigo/utils.py", line 27
    def dbg(*objects, file=sys.stderr, flush=True, **kwargs):
                         ^
SyntaxError: invalid syntax
christine_cheng@instance-1:~/minigo$  which gdb | xargs grep -a python
christine_cheng@instance-1:~/minigo$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by tommadams** [comment]
I never saw anything like that on my end. I'm using the exact same version of Python too.

I've just push another commit, can you re-pull and run `BOARD_SIZE=9 python ml_perf/get_data.py` again please?

**Comment by tommadams** [comment]
It's possible that the version of python being launched by as a subprocess is different for some reason. Are you using a virtual env?

Can you add the following to the top of `main` in `ml_perf/get_data.py` and compare against which python binary & version you expect to be running?

```
print(utils.wait(utils.checked_run('which', 'python')))
print(utils.wait(utils.checked_run('python', '--version'))) 
```

**Comment by tommadams** [comment]
Also, what happens if you run `python freeze_graph.py --model_path=ml_perf/target/9/target --use_tpu=false` directly?

**Pull request merged**
