### PR TITLE
Prep WORKSPACE for bazel >= 0.23

### PR DESCRIPTION
**Pull request by sethtroisi**

### CODE REVIEW

**Comment by tommadams** [comment]
Sorry, just saw this: I have no idea why this doesn't work

**Comment by sethtroisi** [comment]
Weirdly "./cc/json.h:18:73: fatal error: external/com_github_nlohmann_json_single_header/file/json.hpp: No such file or directory"

**Comment by tommadams** [comment]
Ah... it might be that you need to update Bazel in the base image.

I recently updated the documentation and scripts for updating the Docker images, so hopefully the instructions should still work:

https://github.com/tensorflow/minigo/tree/master/testing#updating-continuous-integration-tests
https://github.com/tensorflow/minigo/blob/9fc09ee0ad5a061eda9c19ace5b163caf8513d5f/cluster/base/Dockerfile#L41

**Comment by tommadams** [comment]
I think PR #942 covered this: we're up to Bazel 0.24.1 now.

**Pull request closed without merging**
