### PR TITLE
Autofmt all python

### PR DESCRIPTION
**Pull request by Kashomon**
Autoformat all the python files with autopep8

### CODE REVIEW

**Comment by Kashomon** [comment]
I basically just ran: autopep8 --in-place *.py

**Comment by Kashomon** [comment]
For: https://github.com/tensorflow/minigo/issues/30

Not fixed yet. Will need to hook it up as a presubmit and add instructions.

**Comment by killerducky** [comment]
I ran autopep8 on dual_net.py, and I get a few changes from what is in master. Did you run with --max-line-length other than default 79? It also added a blank line after each class declarations.

```
-        probabilities, value = outputs['policy_output'], outputs['value_output']
+        probabilities, value = outputs[
+            'policy_output'], outputs['value_output']
```

**Comment by Kashomon** [comment]
I left it at the default.

**Comment by killerducky** [comment]
Ok what else could be the difference? I have autopep8 0.9.1. Anything else?

**Comment by Kashomon** [comment]
Ah. That's a pretty old version

```shell
autopep8 --version
autopep8 1.3.4 (pycodestyle: 2.3.1)
```

**Comment by killerducky** [comment]
That's what ubuntu pulled when I did apt install python-autopep8.  :(

**Pull request merged**
