### PR TITLE
Use dynamic parent Q for children's prior

### PR DESCRIPTION
**Pull request by killerducky**
As the search collects more data, update unvisited children with the new more accurate prior.

This is an alternative to #41. LZ is testing this now https://github.com/gcp/leela-zero/pull/866, so far it is slightly worse than the current FPU reduction code in LZ (140-162 = 46%). But IMO it's still better since it seems more logical.

Here are my test results for minigo.

```
                                 wins              black         white       avg cpu
mgbase-000199-lightning-r-800       5  7.69%       3   9.09%     2   6.25%    239.29
mgdynpq-000199-lightning-r-800     60 92.31%       30 93.75%     30 90.91%    250.58
                                                   33 50.77%     32 49.23%
```

### CODE REVIEW

**Comment by amj** [comment]
This looks awesome, thanks for doing it!  Do you have an idea if this change affects playout speed?  I don't think we've got any instructions for how to profile it, but is that something you'd be able to do?  MCTS is the most executed code in any given game, by far, and it can be pretty easy to fall off the numpy-optimized paths.

**Comment by killerducky** [comment]
This code needs to account for virtual losses. I'll work on it later.

**Comment by amj** [comment]
We've learned some interesting things here ;)  Closing as obsolete.

**Pull request closed without merging**
